# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run integration tests
      run: |
        $dir = "$env:USERPROFILE\AppData\Roaming\JetBrains\consentOptions"
        mkdir -Path $dir
        cp -Path .github/workflows/accepted -Destination $dir
        $registryPath = "HKCU:\Software\JavaSoft\Prefs\jetbrains\privacy_policy"
        New-Item -Path $registryPath -Force
        New-ItemProperty -Path $registryPath -Name accepted_version -Value "2.1"
        Start-Process .\gradlew.bat -ArgumentList "runIdeForUiTests -PideaVersion=2020.2" -WindowStyle hidden
        .\gradlew.bat integrationTest
      shell: powershell

    

