name: Itests

on:
  push:
    branches: [ itests ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests
      run: |
        sudo apt-get install xvfb
        export DISPLAY=:99.0
        Xvfb -ac :99 -screen 0 1920x1080x16 &
        ./gradlew runIdeForUiTests &
        ./gradlew integrationTests

