name: Itests

on:
  push:
    branches: [ itests ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests
      run: |
        Xvnc :99 -geometry 1920x1080 &
        export DISPLAY=:99
        ./gradlew runIdeForUiTests -PideaVersion=2020.1 & 
        ./gradlew integrationTest

